#LOGO
favicon: /favicon/favicon.png

#motto
motto: Make the world better

#menu
menu:
	home: /
	tags: /tags
	archives: /archives
	categories: /categories
	
#since
since: 2019

#content
excerpt_link: more

#social
social:
    Github: https://github.com/advancevillage/hexo-theme-otaku
    Blog: https://advancevillage.github.io
    Csdn: https://blog.csdn.net/cugriver
#    Weibo: http://localhost:4000
#    Email: http://localhost:4000
#    Phone: http://localhost:4000
#    Author: http://localhost:4000