#LOGO
favicon: /favicon/favicon.png

#motto
motto: Make the world better

#menu
menu:
	home: /
	tags: /tags
	categories: /categories
	archives: /archives
	
#since
since: 2019

#content
excerpt_link: more

#social
social:
#    Weibo: http://localhost:4000
#    Email: http://localhost:4000
#    Phone: http://localhost:4000
#    Author: http://localhost:4000
